# Generated by Django 3.2.25 on 2024-04-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0205_add_reject_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='format_name',
            field=models.CharField(choices=[('Ultimate', 'Ultimate'), ('atcoder', 'AtCoder'), ('default', 'Default'), ('ecoo', 'ECOO'), ('icpc', 'ICPC'), ('ioi', 'IOI (pre-2016)'), ('ioi16', 'IOI'), ('vnoj', 'VNOJ')], default='default', help_text='The contest format module to use.', max_length=32, verbose_name='contest format'),
        ),
    ]
