# Generated by Django 3.2.25 on 2024-04-30 09:38

import re

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0206_alter_contest_format_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestproblem',
            name='hidden_subtasks',
            field=models.CharField(blank=True, help_text='Only for IOI format. Seperated by commas, e.g: 2, 3, 7', max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Invalid format')], verbose_name='hidden subtasks'),
        ),
    ]
