# Generated by Django 3.2.25 on 2024-04-30 10:17

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0207_contestproblem_hidden_subtasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestproblem',
            name='hidden_subtasks',
            field=models.CharField(blank=True, help_text='Only for IOI format. Seperated by commas, e.g: 2, 3, 7', max_length=50, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\ \\d+)*\\Z'), code='invalid', message='Invalid format')], verbose_name='hidden subtasks'),
        ),
    ]
