# Generated by Django 3.2.25 on 2024-05-14 01:55

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0207_alter_problemdata_custom_checker'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttag',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='tag full name'),
        ),
    ]
