# Generated by Django 3.2.25 on 2024-05-14 03:01

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0208_contesttag_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationbar',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='hidden'),
        ),
    ]
