# Generated by Django 3.2.25 on 2024-05-24 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0209_navigationbar_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='points',
            field=models.IntegerField(help_text='Points awarded for problem completion. Points are displayed with a "p" suffix if partial.', validators=[django.core.validators.MinValueValidator(800), django.core.validators.MaxValueValidator(3500)], verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='points',
            field=models.IntegerField(null=True, verbose_name='points granted'),
        ),
    ]
