# Generated by Django 3.2.25 on 2024-06-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0210_scale_problem_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=1000)),
                ('short_code', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
