# Generated by Django 3.2.25 on 2024-08-10 06:42

import django.core.validators
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0211_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ip_auth',
            field=models.GenericIPAddressField(
                blank=True,
                null=True,
                unique=True,
                verbose_name='IP-based authentication',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='vnoj_points',
            field=models.IntegerField(
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name='comment',
            name='page',
            field=models.CharField(
                db_index=True,
                max_length=34,
                validators=[
                    django.core.validators.RegexValidator(
                        '^\\w+:[a-z0-9A-Z_]+$',
                        'Page code must be ^\\w+:[a-z0-9A-Z_]+$',
                    ),
                ],
                verbose_name='associated page',
            ),
        ),
        migrations.AlterField(
            model_name='commentlock',
            name='page',
            field=models.CharField(
                db_index=True,
                max_length=34,
                validators=[
                    django.core.validators.RegexValidator(
                        '^\\w+:[a-z0-9A-Z_]+$',
                        'Page code must be ^\\w+:[a-z0-9A-Z_]+$',
                    ),
                ],
                verbose_name='associated page',
            ),
        ),
        migrations.AlterField(
            model_name='submission',
            name='points',
            field=models.FloatField(
                null=True,
                verbose_name='points granted',
            ),
        ),
    ]
