# Generated by Django 3.2.25 on 2024-07-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0211_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationbar',
            name='fa_icon',
            field=models.CharField(default='fa-solid fa-poo', max_length=40, verbose_name='icon'),
        ),
    ]
